name: Assign Issues to Project(s)
on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
      - name: Assign NEW issues and NEW pull requests to project 1
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          github.event_name == 'issues' && (
            github.event.action == 'opened' ||
            contains(github.event.issue.labels.*.name, 'bug') ||
            contains(github.event.issue.labels.*.name, 'enhancement')
          )
        with:
          project: 'https://github.com/PartyLich/bandcamp_downloader/projects/1'
